pfsextract -d fixed

diff --git a/project-files/usr/bin/pfsextract b/project-files/usr/bin/pfsextract
--- a/project-files/usr/bin/pfsextract
+++ b/project-files/usr/bin/pfsextract
@@ -46,7 +46,6 @@ extract_simple () {
 		rm -R ${dir}${PFSDIR} 2>/dev/null 
 		return 0 # need zero exit code
 	fi
-    
  }
 
 extract_contaner () {
@@ -58,7 +57,7 @@ pfsinfo "$pfs"   |while read m ;do
 	else 
 		echo $m |grep -q ":" && continue
     fi
-    
+  
     eval echo  "package: $m    -- processing..." $devnull
     m=$(echo $m |sed 's#:#/submod/mount/#g')
     n="$(mkaufs || exitmsg "mkaufs error" 2)"
@@ -87,10 +86,14 @@ pfsinfo "$pfs"   |while read m ;do
     done
       
     [ $dir ] || dir=$(basename $pfs |sed "s/\.${EXT}$//")
-	if [ "$d" ] ; then	
-		mkdir -p "$dir/$m" && cp -a "$SYSMNT/changes$nn"/* "$dir/$m" &&
-		rm -R $dir/$m$PFSDIR
-	elif [ "$i" ] ; then
+	if [ "$nopfs" ] ; then
+		moddirname=$(basename $m)
+		#submod names may be equal
+		[ -d  "$dir/$moddirname" ] && moddirname=${moddirname}_$RANDOM 
+		mkdir -p "$dir/${moddirname}" 
+		cp -a "$SYSMNT/changes$nn"/* "$dir/${moddirname}/" &&
+		rm -rf $dir/${moddirname}/$PFSDIR
+	elif [ "$install" ] ; then
 	    mklist "$SYSMNT/changes$nn" "$SYSMNT/aufs$nn" "$(basename $m)" 
 		cp -a "$SYSMNT/changes$nn"/* /
 		mv -f ${PFSDIR}/mount/$m ${PFSDIR}/install/
@@ -98,7 +101,9 @@ pfsinfo "$pfs"   |while read m ;do
     else
 		touch "$SYSMNT/aufs$nn/${PFSDIR}"
 		cp -fr "$SYSMNT/aufs$nn/${PFSDIR}/mount/$m/submod/mount"  "$SYSMNT/changes$nn/${PFSDIR}/"  2>/dev/null || rm -rf $SYSMNT/changes$nn/${PFSDIR} 
-		mkdir -p "$dir" && mksqmod "$SYSMNT/changes$nn" "$dir/"$(basename $m)".$EXT"
+		modname="$dir/"$(basename $m)".$EXT"
+		[ -f $modname ] && modname="$dir/"$(basename $m)_$RANDOM".$EXT"
+		mkdir -p "$dir" && mksqmod "$SYSMNT/changes$nn" $modname
     fi
     delaufs $nn ; echo ''
 done 
@@ -129,14 +134,14 @@ for arg in $argslist
 do
   case "${arg}" in
     "-o" | "--out-dir") onuserout="on";;
-    "-d" | "--nopfs") d=yes ;;
-    "-i" | "--install") i=yes ;;
+    "-d" | "--nopfs") nopfs=yes ;;
+    "-i" | "--install") install=yes ;;
     "-h" | "--help")  HLP ;;
     "-q" | "--quiet" ) devnull='>/dev/null' ;;
     "-no-progress" | "--no-progress") noprogress="-no-progress";;
     "-processors"  | "--processors" ) numproc="on";;
     "-f" | "--fast"  ) [ "$compression_fast" ] && compression="$compression_fast" || compression="gzip";;
-    "-"*[A-Za-z]*) echo "$(basename "$0"): invalid option -- '$(echo ${arg} | tr -d '-')'" >&2; HLP; exit 1;;
+    "-"*[A-Za-z]*) echo "$(basename "$0"): invalid option: '$(echo ${arg})'" >&2; HLP; exit 1;;
     *) if [ "${onuserout}" = "on" ]; then dir="${arg}"
         elif [ "${numproc}" = "on" ]; then useproc="-processors ${arg}"
         else sourcelist="${sourcelist} ${arg}"; fi
@@ -151,7 +156,7 @@ checksfsxzb >/dev/null 2>&1
 exitmsg "Kernel is not support squashfs/aufs" $?
 wh="-regex -e ".wh..wh.""
 
-
+# find module in arg list
 for item in $sourcelist ; do
 	if [ "$(fs_type $item)" == "squashfs" ] ; then
 	pfs=$item
@@ -160,13 +165,34 @@ for item in $sourcelist ; do
 	fi 
 done
 
+
 [ ! $pfs ] &&  [ $i ]  && [ -d $sourcelist ] && installDir
 [ $pfs ] || exitmsg "There is no source pfs module" 2 
-#echo $sourcelist  |grep -q [[:alnum:]] || unset sourcelist
-sourcelist="`echo $sourcelist |tr -d " "`"
-if [ "$(unsquashfs -l ${pfs} |grep ${PFSDIR}/mount |egrep '.files$' |wc -l)" -lt 2 ];then
-	extract_simple
+
+#удаляем $sourcelist если  он существует, но  состоит из одних  пробелов, такое может получиться  после разбора параметров.
+echo $sourcelist  |grep -q [[:alnum:]] || unset sourcelist 
+
+pfsInfo=$(pfsinfo $pfs)
+if ! [ "$sourcelist" ] ; then
+	if  [ $nopfs ] ; then
+		for a in $pfsInfo ; do 
+			[ $(echo $pfsInfo |sed 's/ /\n/g' | grep ^${a}  | wc -l) -eq 1 ]  && sourcelist="$sourcelist $a"
+		done
+    else
+		for a in $pfsInfo ; do
+			echo $a |grep -qv ":"  && sourcelist="$sourcelist $a"
+		done 
+	fi
 else
-	extract_contaner
+	checked=""
+	for m in $pfsInfo ;do
+		echo " $sourcelist " |grep -q   "[[:space:]]$m[[:space:]]" && checked="$checked $m"
+	done
+	sourcelist="$checked"
 fi
 
+if [ "$(unsquashfs -l ${pfs} |grep ${PFSDIR}/mount |egrep '.files$' |wc -l)" -lt 2 ];then
+	extract_simple
+else	
+	extract_contaner
+fi
