merged from pfsget branch

diff --git a/project-files/usr/bin/pfsextract b/project-files/usr/bin/pfsextract
--- a/project-files/usr/bin/pfsextract
+++ b/project-files/usr/bin/pfsextract
@@ -12,9 +12,13 @@ HLP(){
 echo "\
 $(basename $0) - Распаковщик для модулей pfs
 Использование:
-    $(basename $0) file.pfs - если модуль составной - разобрать на составляющие модули в папку ./file 
-    $(basename $0) file.pfs - если модуль простой - распаковать
-    $(basename $0) file.pfs pack1 pack2 - извлечь из file.pfs только модули pack1 и pack2 
+    $(basename $0) file.$EXT - если модуль составной - разобрать на составляющие модули в папку ./file 
+                          на один уровень вложенности 
+    $(basename $0) file.$EXT --nopfs  - разобрать составной модуль на составляющие на всю глубину вложенности,
+                                   результат не паковать.
+    $(basename $0) file.$EXT - если модуль простой - распаковать
+    $(basename $0) file.$EXT pack1 pack2 - извлечь из file.$EXT только модули pack1 и pack2, 
+                                      имена в формате pfsinfo module.$EXT 
     
 Параметры (ключи):
 	-i / --install   распаковать в систему т.е. \"установить\"
@@ -28,7 +32,7 @@ $(basename $0) - Распаковщик для модулей pfs
 
 extract_simple () {
 #unsquashfs non component-pfs or simple squashfs  
-    [ "$sourcelist" ] && exitmsg "File '${pfs}' is not component-pfs.  Can't extract packages: $sourcelist" 1
+    #[ "$sourcelist" ] && exitmsg "File '${pfs}' is not component-pfs.  Can't extract packages: $sourcelist" 1
     if [ $i ] ; then
 		dir="/" && mkdir -p ${PFSDIR}/install/
     else
@@ -57,14 +61,20 @@ extract_contaner () {
 #extract packages from contaner
 for m in $sourcelist ; do
     eval echo  "package: $m    -- processing..." $devnull
-    m=$(echo $m |sed 's#:#/submod/mount/#g')
+    m=$(echo $m |sed 's#/#/submod/mount/#g')
     n="$(mkaufs || exitmsg "mkaufs error" 2)"
 	nn="$(echo "$n" | sed -n 's/^.*\([0-9]\)$/\1/p')"
 	[ -d "$n" ] || exitmsg "error mounting aufs" 3
     bundle=$(addlayer "$nn" "$pfs" || exitmsg "can't insert layer to aufs $n" 5)
      
     cat "${n}${PFSDIR}/mount/${m}/pfs.files" | while read F; do 
-	touch "$n$F" || cp -a "$bundle/$F" "${n}$(dirname "$F")"
+	touch "$n$F" 
+	if ! [ -e "$SYSMNT/changes$nn/$F" ] ; then
+		pushd "$bundle"
+		cp -a --parents "$(echo "$F" |sed 's:^/::')" "${n}/"
+		popd
+	fi
+	[ -e "$SYSMNT/changes$nn/$F" ] || echo "Warning. Cannot extract $F"
     done
        
     emp="$SYSMNT/aufs$nn/${PFSDIR}/mount/$m/pfs.dirs.empty"
@@ -95,7 +105,17 @@ for m in $sourcelist ; do
 		eval echo  "package: $m  install complete" $devnull 
     else
 		touch "$SYSMNT/aufs$nn/${PFSDIR}"
-		cp -fr "$SYSMNT/aufs$nn/${PFSDIR}/mount/$m/submod/mount"  "$SYSMNT/changes$nn/${PFSDIR}/"  2>/dev/null || rm -rf $SYSMNT/changes$nn/${PFSDIR} 
+		if [ -d "$SYSMNT/aufs$nn${PFSDIR}/mount/$m/submod/mount" ] ; then
+			cp -fr "$SYSMNT/aufs$nn${PFSDIR}/mount/$m/submod/mount"  "$SYSMNT/changes$nn/${PFSDIR}/"  
+		else 
+			# сохраняем спек
+			mkdir -p "$SYSMNT/changes$nn${PFSDIR}/mount/$(basename $m)"
+			find "$SYSMNT/aufs$nn${PFSDIR}/mount/$m/" -type f | while read aaa ; do 
+			[ "$(basename $aaa)" = 'pfs.files' -o "$(basename $aaa)" = 'pfs.dirs.empty' ] && continue 
+			cp -f  "$aaa" "$SYSMNT/changes$nn/${PFSDIR}/mount/$(basename $m)/"
+			done
+		fi	
+		#rm -rf $SYSMNT/changes$nn/${PFSDIR} 
 		modname="$dir/"$(basename $m)".$EXT"
 		[ -f $modname ] && modname="$dir/"$(basename $m)_$RANDOM".$EXT"
 		mkdir -p "$dir" && mksqmod "$SYSMNT/changes$nn" $modname
@@ -107,7 +127,7 @@ done
 installDir ()  {
 sourcedir=$(echo $sourcelist |sed 's:^\ *::')
 eval echo "directory: $sourcedir installing..." $devnull 
-mklist "$sourcedir"   /
+mklist source_root="$sourcedir"   dest_root='/'
 cp -a "$sourcedir"/*   /
 mkdir -p ${PFSDIR}/install/
 mv -f ${PFSDIR}/mount/$(basename "${sourcedir}") ${PFSDIR}/install/
@@ -152,21 +172,20 @@ exitmsg "Kernel is not support squashfs/aufs" $?
 wh="-regex -e ".wh..wh.""
 
 # find module in arg list
+
 for item in $sourcelist ; do
 	if [ "$(fs_type $item)" = "squashfs" ] ; then
-	pfs=$item
-	sourcelist=$(echo "$sourcelist" |sed "s:"$item"::")
-	break
+		pfs=$item
+		break
 	fi 
 done
-
+sourcelist=$(echo "$sourcelist" |sed 's#'"$pfs"'##')
 
 [ ! $pfs ] &&  [ $i ]  && [ -d $sourcelist ] && installDir
 [ $pfs ] || exitmsg "There is no source pfs module" 2 
 
 #удаляем $sourcelist если  он существует, но  состоит из одних  пробелов, такое может получиться  после разбора параметров.
-echo $sourcelist  |grep -q [[:alnum:]] || unset sourcelist 
-
+echo "$sourcelist"  |grep  -q "[[:alnum:]]" || unset sourcelist  
 pfsInfo=$(pfsinfo $pfs)
 if ! [ "$sourcelist" ] ; then
 	if  [ $nopfs ] ; then
@@ -175,19 +194,19 @@ if ! [ "$sourcelist" ] ; then
 		done
     else
 		for a in $pfsInfo ; do
-			echo $a |grep -qv ":"  && sourcelist="$sourcelist $a"
+			echo $a |grep -qv "/"  && sourcelist="$sourcelist $a"
 		done 
 	fi
 else
 	checked=""
 	for m in $pfsInfo ;do
-		echo " $sourcelist " |grep -q   "[[:space:]]$m[[:space:]]" && checked="$checked $m"
+		echo " $sourcelist " |grep  -qF " $m " && checked="$checked $m"
 	done
 	sourcelist="$checked"
 fi
 
 if [ "$(unsquashfs -l ${pfs} |grep ${PFSDIR}/mount |egrep '.files$' |wc -l)" -lt 2 ];then
-	extract_simple
-else	
-	extract_contaner
+		extract_simple
+else
+		extract_contaner
 fi
