pfsmerge-dir like mrpfs

diff --git a/project-files/usr/bin/pfsmerge-dir b/project-files/usr/bin/pfsmerge-dir
--- a/project-files/usr/bin/pfsmerge-dir
+++ b/project-files/usr/bin/pfsmerge-dir
@@ -9,22 +9,25 @@ if [ $? -gt 0 ]; then
   exitmsg "Kernel not support PFS!" 1
 fi
 
-n="$(mkaufs || exitmsg "mkaufs error" 2)"
-nn="$(echo "$n" | sed -n 's/^.*\([0-9]\)$/\1/p')"
-[ "$(echo "$n" |egrep '/aufs[1-9]$')" ] || exitmsg "error mounting aufs" 3
-
 HLP(){
-echo "Usage: $0 DIRECTORY
+echo "Usage: $0 <list of sources> -o out.pfs
     Collect DIRECTORY/DIRECTORYS to PFS.pfs" && exit 1
 }
 
-##mkpfs(
-compression="xz"
-for arg in "$@"
+argslist="$@"
+if  echo $argslist |grep -q "\-*comp .*" ; then
+	compression="$(echo $@ |sed 's/^.*\-*comp//')"
+	argslist="$(echo $@ |sed 's/\-*comp.*$//')"
+fi
+
+
+
+sourcelist=""
+for arg in $argslist
 do
   case "${arg}" in
     "-o" | "--out-file") onuserout="on";;
-    "-?" | "--help")  HLP ;exit 1;;
+    "-h" | "--help")  HLP ;exit 1;;
     "-p" | "--name" | "--name-pack" | "--name-package") usepkname="on";;
     "-n" | "--no-dirs-empty") dirs="off";;
     "-m" | "--md5") md5cr="on";;
@@ -36,45 +39,32 @@ do
     *) if [ "${usepkname}" = "on" ]; then packname="${arg}"
        elif [ "${onuserout}" = "on" ]; then userout="${arg}"
        elif [ "${numproc}" = "on" ]; then useproc="-processors ${arg}"
-       else pfsdir="${arg}"; fi
+       else sourcelist="${sourcelist} ${arg}"; fi
        onuserout="off"; usepkname="off"; usindlib="off"; numproc="off";;
   esac
 done
 
-pwddir="$(pwd)"
-[ "${pfsdir}" = "" ] && pfsdir="${pwddir}"
-if [ -d "${pfsdir}" ]; then
-  chmod 755 "${pfsdir}"
-  cd "${pfsdir}"
-else
-  exitmsg "Directory \"${pfsdir}\" not found!" 4
-fi
 [ "${packname}" != "" ] && pfsname="${packname}" || pfsname="$(basename "${pfsdir}")"
 echo "${pfsname}"
-###mkpfs)
 
-cd ..
-pfsdir="`readlink -f "${pfsdir}"`"
-d="$(find "${pfsdir}" -maxdepth 1 -type d |tail -n+2)"
-[ -d "$pfsdir" ] 	|| HLP
-[ "$d" ] 	|| HLP
+for source in $sourcelist ;do
+	[ -d $source ] && continue
+	[ "$(fs_type $source)" == "squashfs" ] && continue
+	exitmsg "Type of source \"$source\" is not correct" 2
+done	
 
-while read i ;do
+n="$(mkaufs || exitmsg "mkaufs error" 2)"
+nn="$(echo "$n" | sed -n 's/^.*\([0-9]\)$/\1/p')"
+[ "$(echo "$n" |egrep '/aufs[1-9]$')" ] || exitmsg "error mounting aufs" 3
+
+
+for  i in $sourcelist ;do
     mkmeta "$i" "$n"  && addlayer "$nn" "$i" || exitmsg "can't insert layer to aufs" 5
-done << EOF
-$d
-EOF
+done 
 
-pfsdir2="$pfsdir"
-pfsname="`basename "$pfsdir" _pfs`"
-###mkpfs(
-[ "${pfsdir}" = "${pwddir}" ] && cd ../ || cd "${pwddir}"
-[ "${userout}" = "" ] && userout="./${pfsname}.pfs"
-if [ "${compression}" = "xz" ]; then
-  optionscomp="-Xbcj"; uname -m | grep -q -e "86" -e "32" -e "64" && bcjcomp="x86" || bcjcomp="x86,arm"
-fi
-###mkpfs)
-mksquashfs "${n}" "${userout}" -comp ${compression} -b 512K ${optionscomp} ${bcjcomp} -noappend ${noprogress} ${useproc} &&
-[ $? -ne 0 ] && exitmsg "error create squashfs module" $?
+[ "${userout}" = "" ] && userout="./$(basename $(echo $sourcelist | awk '{print $1}')).pfs"
+
+mksquashfs "${n}" "${userout}" -comp ${compression} -noappend ${noprogress} ${useproc}
+	exitmsg "error create squashfs module" $?
 delaufs "$nn"
-exitmsg "delaufs error" $?
+	exitmsg "delaufs error" $?
