Добавил функциональность copy2ram непосредственно в pfsload. Для использования применяется ключ "-m, --memory". Сделано немного не так, как было в pfsramload: новой tmpfs для каждого файла не создается, он просто копируется в директорию, указанную третьим параметром, или в /tmp/.mountRAM по умолчанию.  Перед копированием проверяется, останется ли там как минимум 128M свободного места.
pfsunload при своей работе проверяет, где лежит отключаемый файл.
Если на tmpfs - значит он был скопирован в ram, в этом случае
файл удаляется для освобождения памяти.

diff --git a/usr/sbin/pfsload b/usr/sbin/pfsload
--- a/usr/sbin/pfsload
+++ b/usr/sbin/pfsload
@@ -3,7 +3,6 @@
 #Version 0.21
 #Modify 26.04.2015
 
-mountdir="/mnt"
 hide="."
 
 for arg in "$@"
@@ -15,18 +14,27 @@ do
     "-r" | "--read-only") romode="yes";;
     "-h" | "--help") infile=""; break;;
     "--nh"|"--no-hide") hide="";;
+    "-m" | "--memory") copy2ram="yes";;
     "-"*[A-Za-z]*) echo "$(basename "$0"): invalid option -- '$(echo ${arg} | tr -d '-')'" >&2; exit 1;;
-    *) [ -z "$infile" ] && infile="${arg}" || mountdir="${arg}";;
+    *) [ -z "$infile" ] && infile="${arg}" \
+	|| { [ -z "$mountdir" ] && mountdir="${arg}" \
+	      || copyramdir="${arg}"
+	    };;
   esac
 done
+[ "$mountdir" ] || mountdir="/mnt"
+[ "$copyramdir" ] || copyramdir="/tmp/.mountRAM"
+minspace=131072
+
 if [ "${infile}" = "" ]; then
-  echo "Usage: $(basename "$0") [OPTIONS] FILESYSTEM [MOUNTDIR]"
+  echo "Usage: $(basename "$0") [OPTIONS] FILESYSTEM [MOUNTDIR [COPYRAMDIR]]"
   echo "${IFS}Options:"
   echo " -u, --upper     Mount filesystem to upper layer (AUFS)."
   echo " -l, --lower     Mount filesystem to lower layer (AUFS)."
   echo " -r, --read-only Mount read-only"
   echo " -n, --no-update Do not check for update caches"
   echo " --nh, --no-hide Do not hide mountpoint in mount dir"
+  echo " -m, --memory    Copy to RAM"
   exit
 fi
 
@@ -64,6 +72,15 @@ mountpoint="${mountdir}/${hide}${fsname}"
 [ -d "${mountpoint}" ] && rmdir "${mountpoint}" 2>/dev/null
 [ -d "${mountpoint}" ] && echo "Object \"${fsfile}\" is mounted!" >&2 && exit 1
 
+if [ "$copy2ram" -a "$devtype" != "dev" ] \
+    && [ -d "$copyramdir" ] || mkdir -p "$copyramdir" ; then
+  diskspace=$(df -aT "$copyramdir" | tail -n 1 | tr -s ' ' | cut -d' ' -f5)
+  filesize=$(du -sk "$fsfile" | cut -f1)
+  [ $(expr $diskspace - $filesize) -gt $minspace ] \
+   && cp -a "$fsfile" "$copyramdir" \
+   && fsfile="$copyramdir/$fsname"
+fi
+
 mkdir -p "${mountpoint}"
 case "${devtype}" in
    "file" )   [ "${romode}" -o "${fstype}" == "squashfs" ] \
@@ -72,8 +89,12 @@ case "${devtype}" in
     "dev" )   [ "${romode}" ] && optmnt="ro" || optmnt="rw"
               mountb -t ${fstype} -o ${optmnt} "${fsfile}" "${mountpoint}" ;;
     "dir" )   mountb -t ${fstype} --bind "${fsfile}" "${mountpoint}" ;;
-esac 
-[ $? -ne 0 ] && echo "Unable to mount \"${fsfile}\" in \"${mountpoint}\"." >&2 && exit 1
+esac
+if [ $? -ne 0 ] ; then
+    echo "Unable to mount \"${fsfile}\" in \"${mountpoint}\"." >&2
+    [ "$fsfile" == "$copyramdir/$fsname" ] && rm -rf "$fsfile"
+    exit 1
+fi
 
 [ "${romode}" -o "${fstype}" == "squashfs" ] && optmnt="=rr+wh" || optmnt="=ro+wh"
 if [ "${mntmode}" != "lower" ]; then
@@ -88,6 +109,7 @@ fi
 if [ $? -ne 0 ]; then
     umountb -d "${mountpoint}"
     rmdir "${mountpoint}"
+    [ "$fsfile" == "$copyramdir/$fsname" ] && rm -rf "$fsfile"
     echo "AUFS error!" >&2
     exit 1
 fi
