Переписан pfsload, обновления кэшей вынесены в pfs-update-caches Изменений не так много, как кажется.  Большой diff из-за изменения обработки ошибок.  Вместо:
<действия>
if [успешно]
 <еще действия>
 if [успешно]
  <еще действия>
  if [успешно]
   <еще действия>
  else
   выход
  fi
 else
  выход
 fi
else
 выход
fi

Сделано:
<действия>
[неуспешно] && выход
<еще действия>
[неуспешно] && выход
<еще действия>
[неуспешно] && выход
<еще действия>

По сути то же самое, а читается легче.

Убрал монтирование через losetup, поскольку не встречал систем, где
не работал бы обычный mount -o loop

Убрал sync, в данном случае в них никакого смысла не вижу.

При добавлении ro слоя в aufs он добавляется в режиме rr+wh, иначе ro+wh

diff --git a/usr/sbin/pfsload b/usr/sbin/pfsload
--- a/usr/sbin/pfsload
+++ b/usr/sbin/pfsload
@@ -36,108 +36,55 @@ fi
 
 if [ "${devtype}" != "dir" ]; then
   diskinfo="$(disktype "${fsfile}" 2>/dev/null)"
-  fstype=""
-  if echo "${diskinfo}" | grep -q -F "squashfs"; then
-    fstype='squashfs'
-  elif echo "${diskinfo}" | grep -q -F "Ext2"; then
-    fstype='ext2'
-  elif echo "${diskinfo}" | grep -q -F "Ext3"; then
-    fstype='ext3'
-  elif echo "${diskinfo}" | grep -q -F "Ext4"; then
-    fstype='ext4'
-  fi
+  fstype=$( echo "${diskinfo}" \
+            |tr [:upper:] [:lower:] \
+            |grep -oE "squashfs|ext[2-4]" )
 else
   fsinfo="$(df -aT "${fsfile}" | tail -n 1 | tr -s ' ' '_' | cut -d'_' -f 2)"
   case "${fsinfo}" in
     "ext2"|"ext3"|"ext4"|"squashfs") fstype="${fsinfo}";;
   esac
 fi
-if [ "${fstype}" = "" ]; then
-  echo "Filesystem not supported!" >&2; exit 1
-fi
+[ "${fstype}" = "" ] && echo "Filesystem not supported!" >&2 && exit 1
+
 fsname="$(basename "${fsfile}")"
-if [ "$(echo "${fsname}" | awk -F. '{print $NF}' | tr A-Z a-z)" = "pfs" ]; then
+if [ "$(echo "${fsname##*.}" | tr A-Z a-z)" = "pfs" ]; then
   checksfsxz >/dev/null
-  if [ $? -gt 0 ]; then
-    echo "Kernel not support PFS!" >&2; exit 1
-  fi
-  [ ! "${mntmode}" ] && mntmode="upper"
+  [ $? -gt 0 ] && echo "Kernel not support PFS!" >&2 && exit 1
 fi
 mountpoint="/mnt/.${fsname}"
 [ -d "${mountpoint}" ] && rmdir "${mountpoint}" 2>/dev/null
-if [ -d "${mountpoint}" ]; then
-  echo "Object \"${fsfile}\" is mounted!" >&2; exit 1
-fi
+[ -d "${mountpoint}" ] && echo "Object \"${fsfile}\" is mounted!" >&2 && exit 1
 
-if [ "${devtype}:${fstype}" = "file:squashfs" ]; then
-  sync
-  freeloop=0
-  looplist="$(losetupb -a)"
-  while true ; do
-    echo "${looplist}" | grep -q -F "/dev/loop${freeloop}" && freeloop="$(expr ${freeloop} + 1)" || break
-  done
-  if [ ! -b /dev/loop${freeloop} ]; then
-    mknod -m660 /dev/loop${freeloop} b 7 ${freeloop}
-    chown root.root /dev/loop${freeloop}
-    sync
-  fi
-  if [ ! -b /dev/loop${freeloop} ]; then
-    echo "Error! Free loop devices is not found!" >&2; exit 1
-  fi
-  losetupb /dev/loop${freeloop} "${fsfile}"
-  status=$?
-else
-  status=0
-fi
-
-if [ ${status} -eq 0 ]; then
-  mkdir -p "${mountpoint}"
-  sync
-  case "${devtype}" in
-    "file" )  if [ "${fstype}" = "squashfs" ]; then
-                mountb -t squashfs -o ro /dev/loop${freeloop} "${mountpoint}" >/dev/null 2>&1
-              else
-                [ "${romode}" ] && optmnt="loop,ro" || optmnt="loop"
-                mountb -t ${fstype} -o ${optmnt} "${fsfile}" "${mountpoint}" >/dev/null 2>&1
-              fi;;
+mkdir -p "${mountpoint}"
+case "${devtype}" in
+   "file" )   [ "${romode}" -o "${fstype}" == "squashfs" ] \
+		&& optmnt="loop,ro" || optmnt="loop"
+	      mountb -t ${fstype} -o ${optmnt} "${fsfile}" "${mountpoint}" ;;
     "dev" )   [ "${romode}" ] && optmnt="ro" || optmnt="rw"
-              mountb -t ${fstype} -o ${optmnt} "${fsfile}" "${mountpoint}" >/dev/null 2>&1;;
-    "dir" )   mountb -t ${fstype} --bind "${fsfile}" "${mountpoint}" >/dev/null 2>&1;;
-  esac 
-  status=$?
-  if [ ${status} -eq 0 ]; then
-    sync
-    if [ "${mntmode}" = "upper" ]; then
-      aufslayer="$(topaufslayer 2>/dev/null)"
-      case "${aufslayer}" in
-        ''|*[!0-9]*) aufslayer=1;;
-      esac
-      mountb -o remount,add:${aufslayer}:"${mountpoint}"=ro / >/dev/null 2>&1
-    else
-      mountb -o remount,append:"${mountpoint}"=ro / >/dev/null 2>&1
-    fi
-    status=$?
-    sync
-    if [ ${status} -eq 0 ]; then
-      if [ "${fupdate}" != "no" ]; then
-        [ "$(find "${mountpoint}/lib/modules" "${mountpoint}/usr/lib/modules" -type f -name "*.ko" 2>/dev/null)" != "" ] && depmod &
-        [ "$(find "${mountpoint}/lib" "${mountpoint}/usr/lib" "${mountpoint}/usr/local/lib" "${mountpoint}/usr/X11R7/lib" -type f -name "*.so" 2>/dev/null)" != "" ] && ldconfig &
-        [ -d "${mountpoint}/usr/share/glib-2.0/schemas/" ] && glib-compile-schemas /usr/share/glib-2.0/schemas/ &
-      fi
-    else
-      umountb -d "${mountpoint}" >/dev/null
-	  rmdir "${mountpoint}" >/dev/null
-	  echo "AUFS error!" >&2; exit ${status}
-    fi
-  else
-    losetupb -d /dev/loop${freeloop}
-    rmdir "${mountpoint}" >/dev/null
-	echo "Unable to mount \"${fsfile}\" in \"${mountpoint}\"." >&2; exit ${status}
-  fi
-else
-  rmdir "${mountpoint}" 2>/dev/null
-  echo "Mount error!" >&2; exit ${status}
-fi
-sync
+              mountb -t ${fstype} -o ${optmnt} "${fsfile}" "${mountpoint}" ;;
+    "dir" )   mountb -t ${fstype} --bind "${fsfile}" "${mountpoint}" ;;
+esac 
+[ $? -ne 0 ] && echo "Unable to mount \"${fsfile}\" in \"${mountpoint}\"." >&2 && exit 1
 
+[ "${romode}" -o "${fstype}" == "squashfs" ] && optmnt="=rr+wh" || optmnt="=ro+wh"
+if [ "${mntmode}" != "lower" ]; then
+    aufslayer="$(topaufslayer 2>/dev/null)"
+    case "${aufslayer}" in
+      ''|*[!0-9]*) aufslayer=1;;
+    esac
+    mountb -o remount,add:${aufslayer}:"${mountpoint}${optmnt}" /
+else
+    mountb -o remount,append:"${mountpoint}${optmnt}" /
+fi
+if [ $? -ne 0 ]; then
+    umountb -d "${mountpoint}"
+    rmdir "${mountpoint}"
+    echo "AUFS error!" >&2
+    exit 1
+fi
+
+if [ "${fupdate}" != "no" ]; then
+    pfs-update-caches "${mountpoint}"
+fi
 exit 0
