fix exit code pfsunload

diff --git a/usr/sbin/pfsunload b/usr/sbin/pfsunload
--- a/usr/sbin/pfsunload
+++ b/usr/sbin/pfsunload
@@ -1,7 +1,7 @@
 #!/bin/sh
 #Unmount filesystem to AUFS (for PuppyRus), by Zay, GPL v3.
-#Version 0.15
-#Modify 28.12.2013
+#Version 0.16
+#Modify 21.01.2014
 
 for arg in "$@"
 do
@@ -42,10 +42,11 @@ if [ -d "${mountpoint}" ]; then
   sync
   rmdir "${mountpoint}" 2>/dev/null
   [ ${status} -eq 0 ] && status=${stataufs}
-  [ ${status} -gt 0 ] && echo "Unmount \"${fsname}\" failed!"
+  [ ${status} -gt 0 ] && echo "Unmount \"${fsname}\" failed!" >&2
   sync
 else
   echo "Object \"${fsname}\" not mounted." >&2
+  status=1
 fi
 
 exit ${status}
